import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

const SENDER_EMAIL = process.env.EMAIL_USER;
const OWNER_EMAIL  = process.env.EMAIL_USER;

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

export async function POST(req) {
  try {
    const { name, email, date, time, reason } = await req.json();

    if (!name || !email || !date || !time) {
      return NextResponse.json({ error: "Required fields missing" }, { status: 400 });
    }

    const mailOptions = {
      from: `"AI Assistant" <${SENDER_EMAIL}>`,
      to: OWNER_EMAIL,
      replyTo: email,
      subject: `🗓️ New Meeting Booked: ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #dc143c;">🗓️ New Meeting Request</h2>
          <p>Your AI assistant has scheduled a new meeting for you.</p>
          <hr />
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Date:</strong> ${date}</p>
          <p><strong>Time:</strong> ${time}</p>
          <p><strong>Reason:</strong> ${reason || "Not specified"}</p>
          <hr />
          <p style="font-size: 12px; color: #666;">This message was generated by your Portfolio AI Assistant.</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true, message: "Meeting scheduled successfully!" });
  } catch (error) {
    console.error("Schedule API Error:", error);
    return NextResponse.json({ error: "Failed to schedule meeting" }, { status: 500 });
  }
}
